{
 "title": "FastAPI Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{job=\"fastapi-app\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Error Rate Percentage",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_requests_total{job=\"fastapi-app\", status=~\"5..\"}[1m])) / sum by (instance) (rate(http_requests_total{job=\"fastapi-app\"}[1m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency (P90)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, instance) (rate(http_request_duration_seconds_bucket{job=\"fastapi-app\"}[5m])))",
     "legendFormat": "P90 - {{instance}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (changes(kube_pod_container_status_restarts_total{container=\"fastapi-app\", job=\"kube-state-metrics\", namespace=\"default\"}[15m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"fastapi-app\", namespace=\"default\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Bytes)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{container=\"fastapi-app\", namespace=\"default\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}