global:
  resolve_timeout: 5m
  # Remove slack_api_url from global - we'll set it per receiver

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: slack-default
  routes:
  - match:
      severity: critical
    receiver: slack-critical
  - match:
      severity: warning
    receiver: slack-default
  - match:
      severity: info
    receiver: slack-default

receivers:
- name: slack-default
  slack_configs:
  - channel: "#alerts-general"
    send_resolved: true
    # Use environment variable directly - this will be injected by Kubernetes
    api_url: "${SLACK_WEBHOOK_URL}"
    title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Instance:* {{ .Labels.instance }}
      *Dashboard:* <{{ .GeneratorURL }}|Prometheus Link>
      {{ end }}

- name: slack-critical
  slack_configs:
  - channel: "#alerts-critical"
    send_resolved: true
    api_url: "${SLACK_WEBHOOK_URL}"
    title: '[CRITICAL] {{ .CommonLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Instance:* {{ .Labels.instance }}
      *Dashboard:* <{{ .GeneratorURL }}|Prometheus Link>
      {{ end }}

# Remove the templates section since we're not using the template file anymore