# monitoring/alertmanager_config.yaml
alertmanager:
  enabled: true # Ensure Alertmanager is enabled
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
    routePrefix: / # Matches --set alertmanager.alertmanagerSpec.routePrefix=/
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack-default
      routes:
      - match:
          severity: critical
        receiver: slack-critical
      - match:
          severity: warning
        receiver: slack-default
      - match:
          severity: info
        receiver: slack-default
    receivers:
    - name: slack-default
      slack_configs:
      - channel: "#alerts-general"
        send_resolved: true
        api_url: secret://alertmanager-slack-webhook/alertmanager_slack_webhook_url
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: '{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Instance:* {{ .Labels.instance }}\n*Dashboard:* <{{ .GeneratorURL }}|Prometheus Link>\n{{ end }}'
    - name: slack-critical
      slack_configs:
      - channel: "#alerts-critical" 
        send_resolved: true
        api_url: secret://alertmanager-slack-webhook/alertmanager_slack_webhook_url
        title: '[CRITICAL] {{ .CommonLabels.alertname }}'
        text: '{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Instance:* {{ .Labels.instance }}\n*Dashboard:* <{{ .GeneratorURL }}|Prometheus Link>\n{{ end }}'