alertmanager:
  alertmanagerSpec:
    routePrefix: /
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
  config: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack-default
      routes:
      - match:
          severity: critical
        receiver: slack-critical
      - match:
          severity: warning
        receiver: slack-default
      - match:
          severity: info
        receiver: slack-default
    receivers:
    - name: slack-default
      slack_configs:
      - channel: "#alerts-general"
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: '{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Instance:* {{ .Labels.instance }}\n*Dashboard:* <{{ .GeneratorURL }}|Prometheus Link>\n{{ end }}'
    - name: slack-critical
      slack_configs:
      - channel: "#alerts-critical"
        send_resolved: true
        title: '[CRITICAL] {{ .CommonLabels.alertname }}'
        text: '{{ range .Alerts }}*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Severity:* {{ .Labels.severity }}\n*Instance:* {{ .Labels.instance }}\n*Dashboard:* <{{ .GeneratorURL }}|Prometheus Link>\n{{ end }}'
  enabled: true
grafana:
  adminPassword: prom-operator
  service:
    type: LoadBalancer
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false