apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi.fullname" . }}-secret 
    app.kubernetes.io/name: {{ include "fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:

  DB_USER: "{{ .Values.secret.dbUser }}"
  DB_PASSWORD: "{{ .Values.secret.dbPassword }}"