apiVersion: v1
kind: Service
metadata:
  name: taskpulse-api
  labels:
    app: taskpulse
spec:
  type: LoadBalancer
  selector:
    app: taskpulse
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
