apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskpulse-api
  labels:
    app: taskpulse
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskpulse
  template:
    metadata:
      labels:
        app: taskpulse
    spec:
      containers:
        - name: taskpulse-api
          image: gcr.io/gcp-learn-102/sresync:v1.0
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "104.154.59.20"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "taskpulse"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: taskpulse-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskpulse-secret
                  key: DB_PASSWORD
            - name: PUBSUB_TOPIC
              value: "taskpulse-topic"
            - name: PUBSUB_SUBSCRIPTION
              value: "taskpulse-subscription"
