apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskpulse-monitor
  namespace: monitoring
  labels:
    release: monitoring  
spec:
  selector:
    matchLabels:
      app: taskpulse
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
